# Generated by Django 4.2.1 on 2023-05-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.DecimalField(decimal_places=2, max_digits=5)),
                ('phone_no', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
