# Generated by Django 4.2.1 on 2023-05-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer_id',
            field=models.IntegerField(default=0),
        ),
    ]
