# Generated by Django 4.2.1 on 2023-05-10 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.date(2023, 5, 10)),
        ),
    ]
